[theme]
base = "light"
primaryColor = "#7C3AED"
backgroundColor = "#FAFAFC"
secondaryBackgroundColor = "#F4F4F6"
textColor = "#111827"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
